services:
  backend:
    build: ./backend
    ports:
      - "8545:8545"
    volumes:
      - ./backend:/app
    working_dir: /app
    # environment:
    #   - NODE_ENV=development
    command: ["npx", "hardhat", "compile"]

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - backend